name: CI Build & Artifact

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      VERSION: ${{ github.event.release.tag_name || 'dev' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm
          
      - name: Install Qt/XCB dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1 libx11-xcb1 \
            libxcb-keysyms1 libxcb-image0 libxcb-shm0 \
            libxcb-icccm4 libxcb-render-util0 libxcb-randr0 \
            libxcb-shape0 libxcb-xinerama0 libxkbcommon-x11-0 \
            libxcb-sync1 libxcb-cursor0 libxcb-glx0

      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Pre-install PyYAML with specific Cython
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0.0"
          pip install --no-build-isolation pyyaml==6.0.1

      - name: Install remaining dependencies
        run: |
          pip install -r requirements.txt

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Package .deb with correct version
        run: |
          fpm -C package -s dir -t deb \
              --name liewa \
              --version "$VERSION" \
              -p liewa.deb

      - name: Upload liewa.deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: liewa-deb
          path: liewa.deb
          
      - name: Get latest release upload URL
        id: get_latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return release.data.upload_url;
      
      - name: Upload liewa.deb to latest release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_latest_release.outputs.result }}
          asset_path: ./liewa.deb
          asset_name: liewa.deb
          asset_content_type: application/vnd.debian.binary-package
