name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write     # required by pypa/gh-action-pypi-publish

jobs:
  release-build:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.event.release.tag_name }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install FPM (if you still need it)
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Install Qt/XCB dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1 libx11-xcb1 \
            libxcb-keysyms1 libxcb-image0 libxcb-shm0 \
            libxcb-icccm4 libxcb-render-util0 libxcb-randr0 \
            libxcb-shape0 libxcb-xinerama0 libxkbcommon-x11-0 \
            libxcb-sync1 libxcb-cursor0 libxcb-glx0

      - name: Install system deps for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Pre-install PyYAML
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0.0"
          pip install --no-build-isolation pyyaml==6.0.1

      - name: Install remaining dependencies
        run: pip install -r requirements.txt

      - name: Install build tools
        run: pip install --upgrade setuptools wheel

      - name: Bump version in setup.py
        run: |
          sed -i "s/^\(\s*version\s*=\s*\).*,/\1'${VERSION}',/" setup.py

      - name: Build package
        run: python -m build

      - name: Upload only liewa dist files
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: |
            dist/liewa-*.tar.gz
            dist/liewa-*-py3-none-any.whl

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: 'https://pypi.org/project/liewa/'
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
